Repository NationalGenomicsInfrastructure/standalone_scripts, pull requests merged in 2022-06, with the labels that each got.

#91 Convert statusdb urls to https
  README.md
  compute_production_stats.py
  compute_undet_index_stats.py
  couchdb_replication.py
  hiseqX_run_times.py
  quota_log.py
  repooler.py
  sample_information_validator.py
  sensorpush_to_statusdb.py
  statusdb_snicuser_checker.py
  update_exchange_rates.py
  upload_robot_logs.py
  userName2NGIname_finder.py
Labels: enhancement, no validation

#92 Fix typo
  sensorpush_to_statusdb.py
Labels: bug, no validation

#93 Fix bug
  update_exchange_rates.py
Labels: no validation
